# Generated by Django 4.2.6 on 2024-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aphorism",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "こもん"),
                    ("rare", "レア"),
                    ("very_rare", "げきれあ"),
                    ("unusual", "いんじゃない"),
                    ("not_very_rare", "なかなかレア"),
                ],
                default="common",
                max_length=20,
            ),
        ),
    ]
