# Generated by Django 4.2.6 on 2024-09-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aphorism",
            name="rarity",
            field=models.IntegerField(
                choices=[(1, "☆"), (2, "☆☆"), (3, "☆☆☆"), (4, "☆☆☆☆"), (5, "☆☆☆☆☆")],
                default="common",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="rarity",
            field=models.IntegerField(
                choices=[(1, "☆"), (2, "☆☆"), (3, "☆☆☆"), (4, "☆☆☆☆"), (5, "☆☆☆☆☆")]
            ),
        ),
    ]
