# Generated by Django 4.2.6 on 2024-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='件数'),
        ),
    ]
