# Generated by Django 4.2.6 on 2024-09-24 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("picture", models.ImageField(upload_to="images/")),
                (
                    "acquision_date",
                    models.DateTimeField(verbose_name="Acquisition date"),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "こもん"),
                            ("rare", "レア"),
                            ("very_rare", "げきれあ"),
                            ("unusual", "いんじゃない"),
                            ("not_very_rare", "なかなかレア"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
