# Generated by Django 4.2.6 on 2024-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_aphorism_rarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aphorism",
            name="rarity",
            field=models.IntegerField(
                choices=[(1, "☆"), (2, "☆☆"), (3, "☆☆☆"), (4, "☆☆☆☆"), (5, "☆☆☆☆☆")],
                default="common",
                max_length=20,
            ),
        ),
    ]
