# Generated by Django 4.2.6 on 2024-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("こもん", "common"),
                    ("れあ", "rare"),
                    ("げきれあ", "very_rare"),
                    ("いいんじゃない", "unusual"),
                    ("なかなかレア", "not_very_rare"),
                ],
                default="common",
                max_length=20,
            ),
        ),
    ]
