# Generated by Django 4.2.6 on 2024-09-25 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_goal_flag_alter_aphorism_rarity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="acquision_date",
        ),
        migrations.AddField(
            model_name="collection",
            name="acquisition_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
