# Generated by Django 4.2.6 on 2024-09-24 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='achievement',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='達成度'),
        ),
    ]
